name: messagex

services:
  backend:
    container_name: messagex-backend
    build:
      context: ./messageX_Backend
    ports:
      - "8080:8080"

  frontend:
    container_name: messagex-frontend
    build:
      context: ./messageX_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
